const data = [
    {
      name: "Veggie Delight",
      imageSrc: "https://source.unsplash.com/random?veggies",
      time: "30 min",
      type: "veg",
      isLiked: false,
      rating: 4.2,
    },
    {
      name: "Chicken Grill",
      imageSrc: "https://source.unsplash.com/random?chicken",
      time: "45 min",
      type: "non-veg",
      isLiked: false,
      rating: 4.5,
    },
    {
      name: "Cheese Pizza",
      imageSrc: "https://source.unsplash.com/random?pizza",
      time: "40 min",
      type: "veg",
      isLiked: false,
      rating: 4.1,
    },
    {
      name: "Steak",
      imageSrc: "https://source.unsplash.com/random?steak",
      time: "60 min",
      type: "non-veg",
      isLiked: false,
      rating: 4.7,
    },
    {
      name: "Grilled Salmon",
      imageSrc: "https://source.unsplash.com/random?salmon",
      time: "50 min",
      type: "non-veg",
      isLiked: false,
      rating: 4.6,
    },
    {
      name: "Tomato Pasta",
      imageSrc: "https://source.unsplash.com/random?pasta",
      time: "35 min",
      type: "veg",
      isLiked: false,
      rating: 4.0,
    },
    {
      name: "Vegan Salad",
      imageSrc: "https://source.unsplash.com/random?salad",
      time: "20 min",
      type: "veg",
      isLiked: false,
      rating: 3.9,
    },
    {
      name: "Fried Chicken",
      imageSrc: "https://source.unsplash.com/random?friedChicken",
      time: "55 min",
      type: "non-veg",
      isLiked: false,
      rating: 4.3,
    },
    {
      name: "Mushroom Risotto",
      imageSrc: "https://source.unsplash.com/random?risotto",
      time: "45 min",
      type: "veg",
      isLiked: false,
      rating: 4.5,
    },
    {
      name: "Burger",
      imageSrc: "https://source.unsplash.com/random?burger",
      time: "30 min",
      type: "non-veg",
      isLiked: false,
      rating: 4.2,
    },
    {
      name: "Paneer Tikka",
      imageSrc:
        "https://images.unsplash.com/photo-1657186618738-9dfbcee196b7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFuZWVyJTIwbWFzYWxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      time: "40 min",
      type: "veg",
      isLiked: false,
      rating: 4.4,
    },
    {
      name: "BBQ Ribs",
      imageSrc: "https://source.unsplash.com/random?ribs",
      time: "70 min",
      type: "non-veg",
      isLiked: false,
      rating: 4.6,
    },
    {
      name: "Caesar Salad",
      imageSrc: "https://source.unsplash.com/random?caesarSalad",
      time: "25 min",
      type: "veg",
      isLiked: false,
      rating: 3.8,
    },
    {
      name: "Fish Tacos",
      imageSrc:
        "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
      time: "35 min",
      type: "non-veg",
      isLiked: false,
      rating: 4.3,
    },
    {
      name: "Chocolate Cake",
      imageSrc: "https://source.unsplash.com/random?chocolateCake",
      time: "90 min",
      type: "veg",
      isLiked: false,
      rating: 4.9,
    },
  ];
  
  export default data;
  